version: "2.2"

services:
  #docker volume create mysql_data
  #docker run -d --name mysql -v mysql_data:/var/lib/mysql -v mysql_config:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=minitwit -p 3306:3306  mysql:8.0
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=minitwit
    ports:
      - "3306:3306"
  #docker build -t api ./apps/api
  #docker run -d --name api --link mysql -e DB_HOST=mysql -e DB_USER=root -e DB_PASSWORD=1234 -e DB_NAME=minitwit -e PORT=3000 -p 3000:3000 api
  api:
    image: samuelmichaud/minitwit-api
    container_name: api
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=minitwit
      - PORT=3000
  #docker build -t frontend ./apps/frontend
  #docker run -d --name frontend -p 5173:5173 -e VITE_API_URL="http://localhost:3000/api/v1" frontend
  frontend:
    image: samuelmichaud/minitwit-frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - './apps/frontend/nginx-conf/default.conf:/etc/nginx/conf.d/default.conf'
volumes:
  mysql_data:
  mysql_config: