version: "2.2"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
  api:
    build: /apps/api
    container_name: api
    env_file:
      - ./.env
    ports:
      - "${NODE_API_LOCAL_PORT}:${NODE_API_DOCKER_PORT}"
    environment:
      - DB_HOST=mysql
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - PORT=$NODE_API_DOCKER_PORT
  frontend:
    build: /apps/frontend
    container_name: frontend
    env_file:
      - ./.env
    ports:
      - "${NODE_FRONTEND_LOCAL_PORT}:${NODE_FRONTEND_DOCKER_PORT}"
    environment:
      - VITE_API_URL=http://localhost:${NODE_API_LOCAL_PORT}/api/v1
